# Generated by Django 6.0.2 on 2026-03-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-customer_id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date', '-order_id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-orderitems_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_id']},
        ),
    ]
